CREATE TABLE IF NOT EXISTS measurement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room VARCHAR(255),
    temperature_c DOUBLE PRECISION,
    humidity_percent DOUBLE PRECISION,
    battery_percent INTEGER,
    ts TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_measurement_room_ts ON measurement (room, ts);
